[package]
name = "chronicle-inx"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "IOTA permanode implemented as an IOTA Node Extension (INX)"
readme = "README.md"
repository = "https://github.com/iotaledger/inx-chronicle"
license = "Apache-2.0"
keywords = [ "iota", "storage", "permanode", "node", "inx" ]
homepage = "https://www.iota.org"

[lib]
name = "chronicle"
path = "src/lib.rs"

[[bin]]
name = "inx-chronicle"
path = "src/main.rs"

[dependencies]
actix = "0.13"
anyhow = "1.0"
async-trait = "0.1"
cfg-if = "1.0"
derive_more = "0.99"
dotenv = "0.15"
env_logger = "0.9"
futures = "0.3"
hex = "0.4"
log = "0.4"
mongodb = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
thiserror = "1.0"
time = "0.3"
tokio = "1.0"

# API
axum = { version = "0.5", optional = true }
hyper = { version = "0.14", optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.2", features = ["cors", "catch-panic", "trace"], optional = true }

# API Metrics
lazy_static = { version = "1.4", optional = true }
pin-project = { version = "1.0", optional = true }
prometheus = { version = "0.13", optional = true }

# Chrysalis pt. 2 types
bee-message-cpt2 = { package = "bee-message", version = "0.1", default-features = false, features = ["serde"] }
bee-rest-api-cpt2 = { package = "bee-rest-api", version = "0.1", default-features = false }

# Stardust types
bee-message-stardust = { git = "https://github.com/iotaledger/bee.git", branch = "shimmer-develop", default-features = false, features = ["std", "serde1", "dto"], package = "bee-message" }
bee-rest-api-stardust = { git = "https://github.com/iotaledger/bee.git", branch = "shimmer-develop", default-features = false, package="bee-rest-api" }

[features]
default = [ "api" ]
api = [ 
    "axum",
    "hyper",
    "tower",
    "tower-http"
]
api-metrics = [ 
    "api",
    "lazy_static",
    "pin-project",
    "prometheus"
]
